# Generated by Django 3.1.7 on 2021-06-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suhyun', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Manager',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Entering', 'Entering'), ('Releasing', 'Releasing')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
